<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <MudAllowedAttributePattern>LowerCase</MudAllowedAttributePattern>
    <MudIllegalParameters>V7CaseSensitive</MudIllegalParameters>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="MudAllowedAttributePattern" />
    <CompilerVisibleProperty Include="MudIllegalParameters" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.44.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
    <PackageReference Include="Microsoft.JSInterop.WebAssembly" Version="10.0.2" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="MudBlazor.Markdown" Version="8.11.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Infra\Infra.csproj" />
  </ItemGroup>

</Project>
